apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend-deployment
  labels:
    app: test-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
      - name: test-backend-container
        image: 876762732971.dkr.ecr.ap-northeast-2.amazonaws.com/test-backend:2920366
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          # RDS 엔드포인트로 연결! (비밀번호는 RDS 생성할 때 입력했던 값 그대로)
          value: "mysql+pymysql://admin:YourStrongPassword123!@test-backend-db.c3aukygqmo1y.ap-northeast-2.rds.amazonaws.com:3306/testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: test-backend-service
spec:
  type: LoadBalancer
  selector:
    app: test-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000